# Generated by Django 4.2.2 on 2023-06-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_personnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
    ]
